search_lyrics:
  name: "Search lyrics"
  fields:
    entity_id:
      required: true
      example: "sensor.foobar_lyrics"
      default: ""
    media_artist:
      required: true
      example: "Protoje"
      default: ""
    media_title:
      required: true
      example: "Mind of a King"
      default: ""
